version: "3"
services:
  postgres:
    image: "postgres:alpine"
    restart: always
    privileged: true
    volumes:
      - /var/linkme/postgres:/var/lib/postgresql/data
  nginx:
    image: "nginx:alpine"
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/linkme/nginx:/etc/nginx/conf.d
      - /var/linkme/web:/var/linkme/web
  linkme-server:
    image: "sheason/linkme-server:latest"
    privileged: true
    volumes:
      - /var/linkme/:/var/linkme/
    restart: always
  linkme-socket:
    image: "sheason/linkme-socket:latest"
    privileged: true
    volumes:
      - /var/linkme/:/var/linkme/
    restart: always